// ══ LARDISH CHARTS — ALL CHART DATA ════════════════════════════════
window.LC = window.LC || {};

LC.WK_DATES = [
  "12/28–01/03","01/04–01/10","01/11–01/17","01/18–01/24",
  "01/25–01/31","02/01–02/07","02/08–02/14","02/15–02/21",
  "02/22–02/28","03/01–03/07","03/08–03/14","03/15–03/21",
  "03/22–03/28","03/29–04/04","04/05–04/11","04/12–04/18",
  "04/19–04/25","04/26–05/02", "05/03-05/09", "05/10-05/16",
  "05/17-05/23","05/24-05/30", "05/31-05/06", "06/07-06/13",
  "06/14-06/20", "06/21-06/27"
];

// Weekly song chart history — 18 weeks, top 5 each
LC.WK_SONGS = [
  [{rank:1, title:"NO TEARS FOR NEW YEARS", artist:"Katy Perry", change:"+1"},
{rank:2, title:"Cozy Little Christmas", artist:"Katy Perry", change:"-1"},
{rank:3, title:"bandaids", artist:"Katy Perry", change:"="},
{rank:4, title:"Beauty And A Beat (feat. Nicki Minaj)", artist:"Justin Bieber", change:"NEW"},
{rank:5, title:"Treat You Better", artist:"Shawn Mendes", change:"NEW"},
{rank:6, title:"Me Too", artist:"Meghan Trainor", change:"+9"},
{rank:7, title:"Confident", artist:"Demi Lovato", change:"NEW"},
{rank:8, title:"Chained To the Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"-4"},
{rank:9, title:"Cool for the Summer", artist:"Demi Lovato", change:"-1"},
{rank:10, title:"Anything Could Happen", artist:"Ellie Goulding", change:"NEW"},
{rank:11, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"-4"},
{rank:12, title:"Lights - Single Version", artist:"Ellie Goulding", change:"NEW"},
{rank:13, title:"Heart Attack", artist:"Demi Lovato", change:"NEW"},
{rank:14, title:"Roar", artist:"Katy Perry", change:"-9"},
{rank:15, title:"Give Your Heart A Break", artist:"Demi Lovato", change:"NEW"},
{rank:16, title:"Malibu", artist:"Miley Cyrus", change:"NEW"},
{rank:17, title:"Love Me Like You Do", artist:"Ellie Goulding", change:"NEW"},
{rank:18, title:"Story of My Life", artist:"One Direction", change:"NEW"},
{rank:19, title:"Lost In Japan", artist:"Shawn Mendes", change:"NEW"},
{rank:20, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"NEW"},
{rank:21, title:"Party In The U.S.A.", artist:"Miley Cyrus", change:"NEW"},
{rank:22, title:"The Climb", artist:"Miley Cyrus", change:"NEW"},
{rank:23, title:"Wonder", artist:"Shawn Mendes", change:"NEW"},
{rank:24, title:"Chlorine", artist:"Twenty One Pilots", change:"NEW"},
{rank:25, title:"Survivor / I Will Survive (Glee Cast Version)", artist:"Glee Cast", change:"NEW"},],
  [{rank:1, title:"bandaids", artist:"Katy Perry", change:"+2"},
{rank:2, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"+9"},
{rank:3, title:"Cool for the Summer", artist:"Demi Lovato", change:"+6"},
{rank:4, title:"Stone Cold", artist:"Demi Lovato", change:"NEW"},
{rank:5, title:"Confident", artist:"Demi Lovato", change:"+2"},
{rank:6, title:"Wonder", artist:"Shawn Mendes", change:"+17"},
{rank:7, title:"We Can't Stop", artist:"Miley Cyrus", change:"NEW"},
{rank:8, title:"Story of My Life", artist:"One Direction", change:"+10"},
{rank:9, title:"Look What You Made Me Do", artist:"Taylor Swift", change:"NEW"},
{rank:10, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"+10"},
{rank:11, title:"Burn", artist:"Ellie Goulding", change:"NEW"},
{rank:12, title:"Lost In Japan", artist:"Shawn Mendes", change:"+7"},
{rank:13, title:"She Will Be Loved", artist:"Maroon 5", change:"NEW"},
{rank:14, title:"ALL THE LOVE", artist:"Katy Perry", change:"NEW"},
{rank:15, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"NEW"},
{rank:16, title:"Love Me Like You Do", artist:"Ellie Goulding", change:"+1"},
{rank:17, title:"Me Too", artist:"Meghan Trainor", change:"-11"},
{rank:18, title:"Legendary Lovers", artist:"Katy Perry", change:"NEW"},
{rank:19, title:"LIFETIMES", artist:"Katy Perry", change:"NEW"},
{rank:20, title:"What Do You Mean?", artist:"Justin Bieber", change:"NEW"},
{rank:21, title:"This Love", artist:"Maroon 5", change:"NEW"},
{rank:22, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"NEW"},
{rank:23, title:"Witness", artist:"Katy Perry", change:"NEW"},
{rank:24, title:"Chained To the Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"-16"},
{rank:25, title:"Not Like The Movies", artist:"Katy Perry", change:"NEW"},],
  [{rank:1, title:"bandaids", artist:"Katy Perry", change:"="},
{rank:2, title:"Confident", artist:"Demi Lovato", change:"+3"},
{rank:3, title:"Cool for the Summer", artist:"Demi Lovato", change:"="},
{rank:4, title:"Stone Cold", artist:"Demi Lovato", change:"="},
{rank:5, title:"Burn", artist:"Ellie Goulding", change:"+6"},
{rank:6, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"+4"},
{rank:7, title:"Story of My Life", artist:"One Direction", change:"+1"},
{rank:8, title:"Anything Could Happen", artist:"Ellie Goulding", change:"NEW"},
{rank:9, title:"Feel This Moment (feat. Christina Aguilera)", artist:"Pitbull", change:"NEW"},
{rank:10, title:"Lights - Single Version", artist:"Ellie Goulding", change:"RE"},
{rank:11, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:12, title:"You & I", artist:"One Direction", change:"NEW"},
{rank:13, title:"She Will Be Loved", artist:"Maroon 5", change:"="},
{rank:14, title:"Sorry Not Sorry", artist:"Demi Lovato", change:"NEW"},
{rank:15, title:"Lost In Japan", artist:"Shawn Mendes", change:"-3"},
{rank:16, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"NEW"},
{rank:17, title:"Treat You Better", artist:"Shawn Mendes", change:"NEW"},
{rank:18, title:"This Love", artist:"Maroon 5", change:"+3"},
{rank:19, title:"Party In The U.S.A.", artist:"Miley Cyrus", change:"NEW"},
{rank:20, title:"Easy Lover (feat. Big Sean)", artist:"Ellie Goulding", change:"NEW"},
{rank:21, title:"Wonder", artist:"Shawn Mendes", change:"-15"},
{rank:22, title:"We Can't Stop", artist:"Miley Cyrus", change:"-15"},
{rank:23, title:"Me Too", artist:"Meghan Trainor", change:"-7"},
{rank:24, title:"Neon Lights", artist:"Demi Lovato", change:"NEW"},
{rank:25, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"NEW"},],
  [{rank:1, title:"bandaids", artist:"Katy Perry", change:"="},
{rank:2, title:"Hello", artist:"Adele", change:"NEW"},
{rank:3, title:"Story of My Life", artist:"One Direction", change:"+4"},
{rank:4, title:"Legendary Lovers", artist:"Katy Perry", change:"NEW"},
{rank:5, title:"Gimme More", artist:"Britney Spears", change:"NEW"},
{rank:6, title:"Confident", artist:"Demi Lovato", change:"-4"},
{rank:7, title:"Cool for the Summer", artist:"Demi Lovato", change:"-4"},
{rank:8, title:"Stone Cold", artist:"Demi Lovato", change:"-4"},
{rank:9, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"+16"},
{rank:10, title:"NO", artist:"Meghan Trainor", change:"NEW"},
{rank:11, title:"Witness", artist:"Katy Perry", change:"RE"},
{rank:12, title:"Bon Appétit (feat. Migos)", artist:"Katy Perry", change:"NEW"},
{rank:13, title:"Wonder", artist:"Shawn Mendes", change:"+8"},
{rank:14, title:"One and Only", artist:"Adele", change:"NEW"},
{rank:15, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+1"},
{rank:16, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"-10"},
{rank:17, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"RE"},
{rank:18, title:"Someone Like You", artist:"Adele", change:"NEW"},
{rank:19, title:"Send My Love (To Your New Lover)", artist:"Adele", change:"NEW"},
{rank:20, title:"Feel This Moment (feat. Christina Aguilera)", artist:"Pitbull", change:"-11"},
{rank:21, title:"When We Were Young", artist:"Adele", change:"NEW"},
{rank:22, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"RE"},
{rank:23, title:"She Will Be Loved", artist:"Maroon 5", change:"-10"},
{rank:24, title:"ALL THE LOVE", artist:"Katy Perry", change:"RE"},
{rank:25, title:"Not Like The Movies", artist:"Katy Perry", change:"RE"},],
  [{rank:1, title:"Hello", artist:"Adele", change:"+1"},
{rank:2, title:"bandaids", artist:"Katy Perry", change:"-1"},
{rank:3, title:"Million Years Ago", artist:"Adele", change:"NEW"},
{rank:4, title:"Send My Love (To Your New Lover)", artist:"Adele", change:"+15"},
{rank:5, title:"When We Were Young", artist:"Adele", change:"+16"},
{rank:6, title:"Stone Cold", artist:"Demi Lovato", change:"+2"},
{rank:7, title:"Cool for the Summer", artist:"Demi Lovato", change:"="},
{rank:8, title:"Confident", artist:"Demi Lovato", change:"-2"},
{rank:9, title:"Love In The Dark", artist:"Adele", change:"NEW"},
{rank:10, title:"All I Ask", artist:"Adele", change:"NEW"},
{rank:11, title:"Aperture", artist:"Harry Styles", change:"NEW"},
{rank:12, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"+5"},
{rank:13, title:"Water Under the Bridge", artist:"Adele", change:"NEW"},
{rank:14, title:"Legendary Lovers", artist:"Katy Perry", change:"-10"},
{rank:15, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"RE"},
{rank:16, title:"Not Like The Movies", artist:"Katy Perry", change:"+9"},
{rank:17, title:"Wonder", artist:"Shawn Mendes", change:"-4"},
{rank:18, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"+4"},
{rank:19, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"RE"},
{rank:20, title:"Witness", artist:"Katy Perry", change:"-9"},
{rank:21, title:"Someone Like You", artist:"Adele", change:"-3"},
{rank:22, title:"Story of My Life", artist:"One Direction", change:"-19"},
{rank:23, title:"Don't You Remember", artist:"Adele", change:"NEW"},
{rank:24, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"-8"},
{rank:25, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"-16"},],
  [{rank:1, title:"Million Years Ago", artist:"Adele", change:"+2"},
{rank:2, title:"bandaids", artist:"Katy Perry", change:"="},
{rank:3, title:"Aperture", artist:"Harry Styles", change:"+8"},
{rank:4, title:"Cool for the Summer", artist:"Demi Lovato", change:"+3"},
{rank:5, title:"Chained To The Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"RE"},
{rank:6, title:"Stone Cold", artist:"Demi Lovato", change:"="},
{rank:7, title:"Hey Hey Hey", artist:"Katy Perry", change:"NEW"},
{rank:8, title:"Witness", artist:"Katy Perry", change:"+12"},
{rank:9, title:"When We Were Young", artist:"Adele", change:"-4"},
{rank:10, title:"Hello", artist:"Adele", change:"-9"},
{rank:11, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+4"},
{rank:12, title:"All I Ask", artist:"Adele", change:"-2"},
{rank:13, title:"Confident", artist:"Demi Lovato", change:"-5"},
{rank:14, title:"Send My Love (To Your New Lover)", artist:"Adele", change:"-10"},
{rank:15, title:"Not Like The Movies", artist:"Katy Perry", change:"+1"},
{rank:16, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"+9"},
{rank:17, title:"Bon Appétit (feat. Migos)", artist:"Katy Perry", change:"NEW"},
{rank:18, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"="},
{rank:19, title:"Love In The Dark", artist:"Adele", change:"-10"},
{rank:20, title:"Someone Like You", artist:"Adele", change:"+1"},
{rank:21, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"-2"},
{rank:22, title:"Story of My Life", artist:"One Direction", change:"="},
{rank:23, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"RE"},
{rank:24, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"NEW"},
{rank:25, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},],
  [{rank:1, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+10"},
{rank:2, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+23"},
{rank:3, title:"Hello", artist:"Adele", change:"+7"},
{rank:4, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:5, title:"Love Is A Game", artist:"Adele", change:"NEW"},
{rank:6, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"RE"},
{rank:7, title:"I Drink Wine", artist:"Adele", change:"NEW"},
{rank:8, title:"Easy On Me", artist:"Adele", change:"NEW"},
{rank:9, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"+15"},
{rank:10, title:"When We Were Young", artist:"Adele", change:"-1"},
{rank:11, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"+7"},
{rank:12, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:13, title:"Send My Love (To Your New Lover)", artist:"Adele", change:"+1"},
{rank:14, title:"Witness", artist:"Katy Perry", change:"-6"},
{rank:15, title:"bandaids", artist:"Katy Perry", change:"-13"},
{rank:16, title:"Love In The Dark", artist:"Adele", change:"+3"},
{rank:17, title:"Cool for the Summer", artist:"Demi Lovato", change:"-13"},
{rank:18, title:"Sunflowers", artist:"Louis Tomlinson", change:"NEW"},
{rank:19, title:"Lemonade", artist:"Louis Tomlinson", change:"NEW"},
{rank:20, title:"Chained To The Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"-15"},
{rank:21, title:"Burn", artist:"Ellie Goulding", change:"RE"},
{rank:22, title:"Bon Appétit (feat. Migos)", artist:"Katy Perry", change:"-5"},
{rank:23, title:"Million Years Ago", artist:"Adele", change:"-22"},
{rank:24, title:"Oh My God", artist:"Adele", change:"NEW"},
{rank:25, title:"Hey Hey Hey", artist:"Katy Perry", change:"-18"},],
  [{rank:1, title:"Teenage Dream", artist:"Katy Perry", change:"NEW"},
{rank:2, title:"I Drink Wine", artist:"Adele", change:"+5"},
{rank:3, title:"Love Is A Game", artist:"Adele", change:"+2"},
{rank:4, title:"Easy On Me", artist:"Adele", change:"+4"},
{rank:5, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+7"},
{rank:6, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-2"},
{rank:7, title:"Confident", artist:"Demi Lovato", change:"RE"},
{rank:8, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"+3"},
{rank:9, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"-7"},
{rank:10, title:"Stone Cold", artist:"Demi Lovato", change:"RE"},
{rank:11, title:"Cool for the Summer", artist:"Demi Lovato", change:"+6"},
{rank:12, title:"Oh My God", artist:"Adele", change:"+12"},
{rank:13, title:"Hello", artist:"Adele", change:"-10"},
{rank:14, title:"Sunflowers", artist:"Louis Tomlinson", change:"+4"},
{rank:15, title:"Can I Get It", artist:"Adele", change:"NEW"},
{rank:16, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-15"},
{rank:17, title:"Chasing Pavements", artist:"Adele", change:"NEW"},
{rank:18, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-9"},
{rank:19, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"-13"},
{rank:20, title:"Send My Love (To Your New Lover)", artist:"Adele", change:"-7"},
{rank:21, title:"Lemonade", artist:"Louis Tomlinson", change:"-2"},
{rank:22, title:"bandaids", artist:"Katy Perry", change:"-7"},
{rank:23, title:"Roar", artist:"Katy Perry", change:"RE"},
{rank:24, title:"Legendary Lovers", artist:"Katy Perry", change:"RE"},
{rank:25, title:"Walking On Air", artist:"Katy Perry", change:"NEW"},],
  [{rank:1, title:"Confident", artist:"Demi Lovato", change:"+6"},
{rank:2, title:"Cool for the Summer", artist:"Demi Lovato", change:"+9"},
{rank:3, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"RE"},
{rank:4, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+5"},
{rank:5, title:"Stone Cold", artist:"Demi Lovato", change:"+5"},
{rank:6, title:"Witness", artist:"Katy Perry", change:"RE"},
{rank:7, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"+1"},
{rank:8, title:"bandaids", artist:"Katy Perry", change:"+14"},
{rank:9, title:"7 rings", artist:"Ariana Grande", change:"NEW"},
{rank:10, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"RE"},
{rank:11, title:"Firework", artist:"Katy Perry", change:"NEW"},
{rank:12, title:"Never Really Over", artist:"Katy Perry", change:"NEW"},
{rank:13, title:"Make You Feel My Love", artist:"Adele", change:"NEW"},
{rank:14, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+5"},
{rank:15, title:"Hello", artist:"Adele", change:"-2"},
{rank:16, title:"Sunflowers", artist:"Louis Tomlinson", change:"-2"},
{rank:17, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"RE"},
{rank:18, title:"Burn", artist:"Ellie Goulding", change:"RE"},
{rank:19, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-3"},
{rank:20, title:"Legendary Lovers", artist:"Katy Perry", change:"+4"},
{rank:21, title:"Easy On Me", artist:"Adele", change:"-17"},
{rank:22, title:"Teenage Dream", artist:"Katy Perry", change:"-21"},
{rank:23, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-17"},
{rank:24, title:"Birthday", artist:"Katy Perry", change:"NEW"},
{rank:25, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"-20"},],
  [{rank:1, title:"Hello", artist:"Adele", change:"+14"},
{rank:2, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+12"},
{rank:3, title:"Unconditionally", artist:"Katy Perry", change:"NEW"},
{rank:4, title:"Aperture", artist:"Harry Styles", change:"RE"},
{rank:5, title:"Cool for the Summer", artist:"Demi Lovato", change:"-3"},
{rank:6, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"+17"},
{rank:7, title:"Chasing Pavements", artist:"Adele", change:"RE"},
{rank:8, title:"Confident", artist:"Demi Lovato", change:"-7"},
{rank:9, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"+1"},
{rank:10, title:"Teenage Dream", artist:"Katy Perry", change:"+12"},
{rank:11, title:"bandaids", artist:"Katy Perry", change:"-3"},
{rank:12, title:"Palaces", artist:"Louis Tomlinson", change:"NEW"},
{rank:13, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"-10"},
{rank:14, title:"Witness", artist:"Katy Perry", change:"-8"},
{rank:15, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+4"},
{rank:16, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"-12"},
{rank:17, title:"Never Really Over", artist:"Katy Perry", change:"-5"},
{rank:18, title:"Firework", artist:"Katy Perry", change:"-7"},
{rank:19, title:"Stone Cold", artist:"Demi Lovato", change:"-14"},
{rank:20, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+5"},
{rank:21, title:"Sunflowers", artist:"Louis Tomlinson", change:"-5"},
{rank:22, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"-15"},
{rank:23, title:"Make You Feel My Love", artist:"Adele", change:"-10"},
{rank:24, title:"Birthday", artist:"Katy Perry", change:"="},
{rank:25, title:"Lemonade", artist:"Louis Tomlinson", change:"NEW"},],
  [{rank:1, title:"Aperture", artist:"Harry Styles", change:"+3"},
{rank:2, title:"Hello", artist:"Adele", change:"-1"},
{rank:3, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"+3"},
{rank:4, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+11"},
{rank:5, title:"seven", artist:"Taylor Swift", change:"NEW"},
{rank:6, title:"Confident", artist:"Demi Lovato", change:"+2"},
{rank:7, title:"Cool for the Summer", artist:"Demi Lovato", change:"-2"},
{rank:8, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+12"},
{rank:9, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+7"},
{rank:10, title:"Teenage Dream", artist:"Katy Perry", change:"="},
{rank:11, title:"Taste Back", artist:"Harry Styles", change:"NEW"},
{rank:12, title:"Stone Cold", artist:"Demi Lovato", change:"+7"},
{rank:13, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"RE"},
{rank:14, title:"Firework", artist:"Katy Perry", change:"+4"},
{rank:15, title:"Wildfire", artist:"Demi Lovato", change:"NEW"},
{rank:16, title:"American Girls", artist:"Harry Styles", change:"NEW"},
{rank:17, title:"Into You", artist:"Ariana Grande", change:"NEW"},
{rank:18, title:"Sunflowers", artist:"Louis Tomlinson", change:"+3"},
{rank:19, title:"Beauty And A Beat (feat. Nicki Minaj)", artist:"Justin Bieber", change:"RE"},
{rank:20, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:21, title:"Burn", artist:"Ellie Goulding", change:"RE"},
{rank:22, title:"Are You Listening Yet?", artist:"Harry Styles", change:"NEW"},
{rank:23, title:"bandaids", artist:"Katy Perry", change:"-12"},
{rank:24, title:"Chasing Pavements", artist:"Adele", change:"-17"},
{rank:25, title:"The Waiting Game", artist:"Harry Styles", change:"NEW"},],
  [{rank:1, title:"American Girls", artist:"Harry Styles", change:"+15"},
{rank:2, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+7"},
{rank:3, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+1"},
{rank:4, title:"seven", artist:"Taylor Swift", change:"+1"},
{rank:5, title:"Never Really Over", artist:"Katy Perry", change:"RE"},
{rank:6, title:"Aperture", artist:"Harry Styles", change:"-5"},
{rank:7, title:"Sunflowers", artist:"Louis Tomlinson", change:"+11"},
{rank:8, title:"Cool for the Summer", artist:"Demi Lovato", change:"-1"},
{rank:9, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-6"},
{rank:10, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"+10"},
{rank:11, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"RE"},
{rank:12, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"-4"},
{rank:13, title:"Firework", artist:"Katy Perry", change:"+1"},
{rank:14, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-1"},
{rank:15, title:"bandaids", artist:"Katy Perry", change:"+8"},
{rank:16, title:"Ready, Steady, Go!", artist:"Harry Styles", change:"NEW"},
{rank:17, title:"Teenage Dream", artist:"Katy Perry", change:"-7"},
{rank:18, title:"Easy On Me", artist:"Adele", change:"RE"},
{rank:19, title:"Taste Back", artist:"Harry Styles", change:"-8"},
{rank:20, title:"Imposter", artist:"Louis Tomlinson", change:"NEW"},
{rank:21, title:"Lemonade", artist:"Louis Tomlinson", change:"RE"},
{rank:22, title:"LIFETIMES", artist:"Katy Perry", change:"RE"},
{rank:23, title:"Palaces", artist:"Louis Tomlinson", change:"RE"},
{rank:24, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"RE"},
{rank:25, title:"Heart Attack", artist:"Demi Lovato", change:"RE"},],
  [{rank:1, title:"Birthday", artist:"Katy Perry", change:"RE"},
{rank:2, title:"LIFETIMES", artist:"Katy Perry", change:"+20"},
{rank:3, title:"ALL THE LOVE", artist:"Katy Perry", change:"RE"},
{rank:4, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+8"},
{rank:5, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"-3"},
{rank:6, title:"Cool for the Summer", artist:"Demi Lovato", change:"+2"},
{rank:7, title:"Wildfire", artist:"Demi Lovato", change:"RE"},
{rank:8, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"+1"},
{rank:9, title:"bandaids", artist:"Katy Perry", change:"+6"},
{rank:10, title:"seven", artist:"Taylor Swift", change:"-6"},
{rank:11, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"="},
{rank:12, title:"exile (feat. Bon Iver)", artist:"Taylor Swift", change:"NEW"},
{rank:13, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-10"},
{rank:14, title:"the last great american dynasty", artist:"Taylor Swift", change:"NEW"},
{rank:15, title:"Firework", artist:"Katy Perry", change:"-2"},
{rank:16, title:"Legendary Lovers", artist:"Katy Perry", change:"RE"},
{rank:17, title:"Stone Cold", artist:"Demi Lovato", change:"RE"},
{rank:18, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"-8"},
{rank:19, title:"Confident", artist:"Demi Lovato", change:"RE"},
{rank:20, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-6"},
{rank:21, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"RE"},
{rank:22, title:"Dangerous Woman", artist:"Ariana Grande", change:"NEW"},
{rank:23, title:"Drag Me Down", artist:"One Direction", change:"NEW"},
{rank:24, title:"Never Really Over", artist:"Katy Perry", change:"-19"},
{rank:25, title:"the 1", artist:"Taylor Swift", change:"NEW"},],
  [{rank:1, title:"exile (feat. Bon Iver)", artist:"Taylor Swift", change:"+11"},
{rank:2, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+3"},
{rank:3, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+1"},
{rank:4, title:"Sunflowers", artist:"Louis Tomlinson", change:"RE"},
{rank:5, title:"Cool for the Summer", artist:"Demi Lovato", change:"+1"},
{rank:6, title:"my tears ricochet", artist:"Taylor Swift", change:"NEW"},
{rank:7, title:"cardigan", artist:"Taylor Swift", change:"NEW"},
{rank:8, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+5"},
{rank:9, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-1"},
{rank:10, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"+8"},
{rank:11, title:"the 1", artist:"Taylor Swift", change:"+14"},
{rank:12, title:"no tears left to cry", artist:"Ariana Grande", change:"NEW"},
{rank:13, title:"Palaces", artist:"Louis Tomlinson", change:"RE"},
{rank:14, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"+6"},
{rank:15, title:"Into You", artist:"Ariana Grande", change:"RE"},
{rank:16, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"-5"},
{rank:17, title:"Imposter", artist:"Louis Tomlinson", change:"RE"},
{rank:18, title:"Lemonade", artist:"Louis Tomlinson", change:"RE"},
{rank:19, title:"bandaids", artist:"Katy Perry", change:"-10"},
{rank:20, title:"the last great american dynasty", artist:"Taylor Swift", change:"-6"},
{rank:21, title:"Liar", artist:"Silia Kapsis", change:"NEW"},
{rank:22, title:"Hello", artist:"Adele", change:"RE"},
{rank:23, title:"Birthday", artist:"Katy Perry", change:"-22"},
{rank:24, title:"What Do You Mean?", artist:"Justin Bieber", change:"RE"},
{rank:25, title:"ALL THE LOVE", artist:"Katy Perry", change:"-22"},],
  [{rank:1, title:"Confident", artist:"Demi Lovato", change:"RE"},
{rank:2, title:"bandaids", artist:"Katy Perry", change:"+17"},
{rank:3, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"+6"},
{rank:4, title:"Cool for the Summer", artist:"Demi Lovato", change:"+1"},
{rank:5, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"-2"},
{rank:6, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"-4"},
{rank:7, title:"Karma", artist:"Taylor Swift", change:"NEW"},
{rank:8, title:"Hello", artist:"Adele", change:"+14"},
{rank:9, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"+1"},
{rank:10, title:"Into You", artist:"Ariana Grande", change:"+5"},
{rank:11, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+5"},
{rank:12, title:"Sunflowers", artist:"Louis Tomlinson", change:"-8"},
{rank:13, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-5"},
{rank:14, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"="},
{rank:15, title:"exile (feat. Bon Iver)", artist:"Taylor Swift", change:"-14"},
{rank:16, title:"Wildfire", artist:"Demi Lovato", change:"RE"},
{rank:17, title:"Stone Cold", artist:"Demi Lovato", change:"RE"},
{rank:18, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"+28"},
{rank:19, title:"Lemonade", artist:"Louis Tomlinson", change:"-1"},
{rank:20, title:"Dangerous Woman", artist:"Ariana Grande", change:"RE"},
{rank:21, title:"Side To Side (feat. Nicki Minaj)", artist:"Ariana Grande", change:"NEW"},
{rank:22, title:"my tears ricochet", artist:"Taylor Swift", change:"-16"},
{rank:23, title:"Palaces", artist:"Louis Tomlinson", change:"-10"},
{rank:24, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"RE"},
{rank:25, title:"cardigan", artist:"Taylor Swift", change:"-18"},],
  [{rank:1, title:"Sunflowers", artist:"Louis Tomlinson", change:"+11"},
{rank:2, title:"Cool for the Summer", artist:"Demi Lovato", change:"+2"},
{rank:3, title:"Dark To Light", artist:"Louis Tomlinson", change:"NEW"},
{rank:4, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-1"},
{rank:5, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+8"},
{rank:6, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"="},
{rank:7, title:"Palaces", artist:"Louis Tomlinson", change:"+16"},
{rank:8, title:"Karma", artist:"Taylor Swift", change:"-1"},
{rank:9, title:"Lemonade", artist:"Louis Tomlinson", change:"+10"},
{rank:10, title:"bandaids", artist:"Katy Perry", change:"-8"},
{rank:11, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"-2"},
{rank:12, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"-7"},
{rank:13, title:"Imposter", artist:"Louis Tomlinson", change:"RE"},
{rank:14, title:"Confident", artist:"Demi Lovato", change:"-13"},
{rank:15, title:"Vodka Cranberry", artist:"Conan Gray", change:"NEW"},
{rank:16, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-2"},
{rank:17, title:"Too Much To Ask", artist:"Niall Horan", change:"NEW"},
{rank:18, title:"Low Rise Jeans", artist:"Demi Lovato", change:"NEW"},
{rank:19, title:"Lavender Haze", artist:"Taylor Swift", change:"NEW"},
{rank:20, title:"Anti-Hero", artist:"Taylor Swift", change:"NEW"},
{rank:21, title:"Wildfire", artist:"Demi Lovato", change:"-5"},
{rank:22, title:"Stone Cold", artist:"Demi Lovato", change:"-5"},
{rank:23, title:"the last great american dynasty", artist:"Taylor Swift", change:"RE"},
{rank:24, title:"Someone Like You", artist:"Adele", change:"RE"},
{rank:25, title:"Mercy", artist:"Shawn Mendes", change:"NEW"},],
  [{rank:1, title:"Vodka Cranberry", artist:"Conan Gray", change:"+14"},
{rank:2, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+4"},
{rank:3, title:"Legendary Lovers", artist:"Katy Perry", change:"RE"},
{rank:4, title:"bandaids", artist:"Katy Perry", change:"+6"},
{rank:5, title:"Sunflowers", artist:"Louis Tomlinson", change:"-4"},
{rank:6, title:"Cool for the Summer", artist:"Demi Lovato", change:"-4"},
{rank:7, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-3"},
{rank:8, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+4"},
{rank:9, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-4"},
{rank:10, title:"ALL THE LOVE", artist:"Katy Perry", change:"RE"},
{rank:11, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"="},
{rank:12, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"RE"},
{rank:13, title:"Low Rise Jeans", artist:"Demi Lovato", change:"+5"},
{rank:14, title:"Dark To Light", artist:"Louis Tomlinson", change:"-11"},
{rank:15, title:"Palaces", artist:"Louis Tomlinson", change:"-8"},
{rank:16, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"RE"},
{rank:17, title:"Lemonade", artist:"Louis Tomlinson", change:"-8"},
{rank:18, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"RE"},
{rank:19, title:"Wildfire", artist:"Demi Lovato", change:"+2"},
{rank:20, title:"Perfect", artist:"One Direction", change:"NEW"},
{rank:21, title:"The One That Got Away", artist:"Katy Perry", change:"NEW"},
{rank:22, title:"Drag Me Down", artist:"One Direction", change:"RE"},
{rank:23, title:"Wide Awake", artist:"Katy Perry", change:"NEW"},
{rank:24, title:"Harleys In Hawaii", artist:"Katy Perry", change:"NEW"},
{rank:25, title:"Lights - Single Version", artist:"Ellie Goulding", change:"RE"},],
  [{rank:1, title:"Thinking Of You", artist:"Katy Perry", change:"NEW"},
{rank:2, title:"Back To December (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:3, title:"Legendary Lovers", artist:"Katy Perry", change:"="},
{rank:4, title:"The One That Got Away", artist:"Katy Perry", change:"+17"},
{rank:5, title:"I Knew You Were Trouble (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:6, title:"Try", artist:"P!nk", change:"NEW"},
{rank:7, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+5"},
{rank:8, title:"…Ready For It?", artist:"Taylor Swift", change:"NEW"},
{rank:9, title:"Sunflowers", artist:"Louis Tomlinson", change:"-4"},
{rank:10, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"-8"},
{rank:11, title:"loml", artist:"Taylor Swift", change:"NEW"},
{rank:12, title:"Perfect", artist:"One Direction", change:"+8"},
{rank:13, title:"Firework", artist:"Katy Perry", change:"RE"},
{rank:14, title:"We Are Never Ever Getting Back Together (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:15, title:"bandaids", artist:"Katy Perry", change:"-11"},
{rank:16, title:"we fell in love in october", artist:"girl in red", change:"NEW"},
{rank:17, title:"Cool for the Summer", artist:"Demi Lovato", change:"-11"},
{rank:18, title:"Witness", artist:"Katy Perry", change:"RE"},
{rank:19, title:"Low Rise Jeans", artist:"Demi Lovato", change:"-6"},
{rank:20, title:"Confident", artist:"Demi Lovato", change:"RE"},
{rank:21, title:"Vodka Cranberry", artist:"Conan Gray", change:"-20"},
{rank:22, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-13"},
{rank:23, title:"Dark To Light", artist:"Louis Tomlinson", change:"-9"},
{rank:24, title:"Unconditionally", artist:"Katy Perry", change:"RE"},
{rank:25, title:"Lover", artist:"Taylor Swift", change:"NEW"},],
    [{rank:1, title:"The One That Got Away", artist:"Katy Perry", change:"+3"},
{rank:2, title:"Legendary Lovers", artist:"Katy Perry", change:"+1"},
{rank:3, title:"I Did Something Bad", artist:"Taylor Swift", change:"NEW"},
{rank:4, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+18"},
{rank:5, title:"6 Inch (feat. The Weeknd)", artist:"Beyoncé", change:"NEW"},
{rank:6, title:"CANCELLED!", artist:"Taylor Swift", change:"NEW"},
{rank:7, title:"…Ready For It?", artist:"Taylor Swift", change:"+1"},
{rank:8, title:"Power", artist:"Katy Perry", change:"NEW"},
{rank:9, title:"Freedom (feat. Kendrick Lamar)", artist:"Beyoncé", change:"NEW"},
{rank:10, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"-4"},
{rank:11, title:"Look What You Made Me Do", artist:"Taylor Swift", change:"RE"},
{rank:12, title:"Elizabeth Taylor", artist:"Taylor Swift", change:"NEW"},
{rank:13, title:"Getaway Car", artist:"Taylor Swift", change:"NEW"},
{rank:14, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"RE"},
{rank:15, title:"The Fate of Ophelia", artist:"Taylor Swift", change:"NEW"},
{rank:16, title:"River Lea", artist:"Adele", change:"NEW"},
{rank:17, title:"Part Of Me", artist:"Katy Perry", change:"NEW"},
{rank:18, title:"bandaids", artist:"Katy Perry", change:"-3"},
{rank:19, title:"Don't Blame Me", artist:"Taylor Swift", change:"NEW"},
{rank:20, title:"Is It Over Now? (Taylor's Version) (From The Vault)", artist:"Taylor Swift", change:"NEW"},
{rank:21, title:"Ruin The Friendship", artist:"Taylor Swift", change:"NEW"},
{rank:22, title:"The One That Got Away - Acoustic", artist:"Katy Perry", change:"NEW"},
{rank:23, title:"This Is Why We Can't Have Nice Things", artist:"Taylor Swift", change:"NEW"},
{rank:24, title:"Formation", artist:"Beyoncé", change:"NEW"},
{rank:25, title:"Ghost", artist:"Katy Perry", change:"NEW"},],
    [{rank:1, title:"Legendary Lovers", artist:"Katy Perry", change:"+1"},
{rank:2, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+2"},
{rank:3, title:"bandaids", artist:"Katy Perry", change:"+15"},
{rank:4, title:"Vodka Cranberry", artist:"Conan Gray", change:"RE"},
{rank:5, title:"Thinking of You", artist:"Katy Perry", change:"RE"},
{rank:6, title:"Part Of Me", artist:"Katy Perry", change:"+11"},
{rank:7, title:"Opalite", artist:"Taylor Swift", change:"NEW"},
{rank:8, title:"Hard Feelings /Loveless", artist:"Lorde", change:"NEW"},
{rank:9, title:"Bangaranga", artist:"DARA", change:"NEW"},
{rank:10, title:"The One That Got Away", artist:"Katy Perry", change:"-9"},
{rank:11, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"RE"},
{rank:12, title:"Wide Awake", artist:"Katy Perry", change:"RE"},
{rank:13, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"+1"},
{rank:14, title:"Sanity", artist:"Louis Tomlinson", change:"NEW"},
{rank:15, title:"Green Light", artist:"Lorde", change:"NEW"},
{rank:16, title:"The Louvre", artist:"Lorde", change:"NEW"},
{rank:17, title:"Ruin The Friendship", artist:"Taylor Swift", change:"+4"},
{rank:18, title:"Teenage Dream", artist:"Katy Perry", change:"RE"},
{rank:19, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"RE"},
{rank:20, title:"I Did Something Bad", artist:"Taylor Swift", change:"-16"},
{rank:21, title:"Hello", artist:"Adele", change:"+8"},
{rank:22, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"RE"},
{rank:23, title:"Last Friday Night (T.G.I.F.)", artist:"Katy Perry", change:"NEW"},
{rank:24, title:"Power", artist:"Katy Perry", change:"-16"},
{rank:25, title:"I Knew You Were Trouble (Taylor's Version)", artist:"Taylor Swift", change:"RE"},],
[
  {rank:1, title:"Bangaranga", artist:"DARA", change:"+8"},
{rank:2, title:"bandaids", artist:"Katy Perry", change:"+1"},
{rank:3, title:"Thinking Of You", artist:"Katy Perry", change:"+2"},
{rank:4, title:"Legendary Lovers", artist:"Katy Perry", change:"-3"},
{rank:5, title:"Part Of Me", artist:"Katy Perry", change:"+1"},
{rank:6, title:"The One That Got Away", artist:"Katy Perry", change:"+4"},
{rank:7, title:"Vodka Cranberry", artist:"Conan Gray", change:"-3"},
{rank:8, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-6"},
{rank:9, title:"Unconditionally", artist:"Katy Perry", change:"RE"},
{rank:10, title:"Roar", artist:"Katy Perry", change:"RE"},
{rank:11, title:"Ruin The Friendship", artist:"Taylor Swift", change:"+6"},
{rank:12, title:"Teenage Dream", artist:"Katy Perry", change:"+6"},
{rank:13, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"RE"},
{rank:14, title:"Michelle", artist:"Noam Bettan & כאן - תאגיד השידור הישראלי", change:"NEW"},
{rank:15, title:"REGARDE !", artist:"Monroe", change:"NEW"},
{rank:16, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-3"},
{rank:17, title:"Chained To The Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"RE"},
{rank:18, title:"Firework", artist:"Katy Perry", change:"RE"},
{rank:19, title:"Never Really Over", artist:"Katy Perry", change:"RE"},
{rank:20, title:"Harleys In Hawaii", artist:"Katy Perry", change:"RE"},
{rank:21, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"RE"},
{rank:22, title:"I Did Something Bad", artist:"Taylor Swift", change:"-2"},
{rank:23, title:"California Gurls (feat. Snoop Dogg)", artist:"Katy Perry", change:"-12"},
{rank:24, title:"Bon Appétit (feat. Migos)", artist:"Katy Perry", change:"RE"},
{rank:25, title:"Andromeda", artist:"LELEK", change:"NEW"},
],
[{rank:1, title:"Legendary Lovers", artist:"Katy Perry", change:"+3"},
{rank:2, title:"Legendary Lovers (Save Me)", artist:"Katy Perry & Chief Keef", change:"NEW"},
{rank:3, title:"Bangaranga", artist:"DARA", change:"-2"},
{rank:4, title:"Unconditionally", artist:"Katy Perry", change:"+5"},
{rank:5, title:"Teenage Dream", artist:"Katy Perry", change:"+7"},
{rank:6, title:"exile (feat. Bon Iver)", artist:"Taylor Swift", change:"RE"},
{rank:7, title:"CANCELLED!", artist:"Taylor Swift", change:"RE"},
{rank:8, title:"cardigan", artist:"Taylor Swift", change:"RE"},
{rank:9, title:"Opalite", artist:"Taylor Swift", change:"RE"},
{rank:10, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-2"},
{rank:11, title:"hate that i made you love me", artist:"Ariana Grande", change:"NEW"},
{rank:12, title:"we can't be friends (wait for your love)", artist:"Ariana Grande", change:"NEW"},
{rank:13, title:"Roar", artist:"Katy Perry", change:"-3"},
{rank:14, title:"Wide Awake", artist:"Katy Perry", change:"RE"},
{rank:15, title:"Harleys In Hawaii", artist:"Katy Perry", change:"+5"},
{rank:16, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"RE"},
{rank:17, title:"This Song", artist:"Conan Gray", change:"NEW"},
{rank:18, title:"the 1", artist:"Taylor Swift", change:"RE"},
{rank:19, title:"Thinking of You", artist:"Katy Perry", change:"-16"},
{rank:20, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+1"},
{rank:21, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-5"},
{rank:22, title:"Bon Appétit (feat. Migos)", artist:"Katy Perry", change:"+2"},
{rank:23, title:"Lover", artist:"Taylor Swift", change:"RE"},
{rank:24, title:"yes, and?", artist:"Ariana Grande", change:"NEW"},
{rank:25, title:"Elizabeth Taylor", artist:"Taylor Swift", change:"RE"},],
[{rank:1, title:"Cool for the Summer", artist:"Demi Lovato", change:"RE"},
{rank:2, title:"hate that i made you love me", artist:"Ariana Grande", change:"+9"},
{rank:3, title:"bandaids", artist:"Katy Perry", change:"RE"},
{rank:4, title:"Bangaranga", artist:"DARA", change:"-1"},
{rank:5, title:"yes, and?", artist:"Ariana Grande", change:"+19"},
{rank:6, title:"Firework", artist:"Katy Perry", change:"RE"},
{rank:7, title:"Roar", artist:"Katy Perry", change:"+6"},
{rank:8, title:"I Kissed A Girl", artist:"Katy Perry", change:"NEW"},
{rank:9, title:"Unconditionally", artist:"Katy Perry", change:"-5"},
{rank:10, title:"Never Really Over", artist:"Katy Perry", change:"RE"},
{rank:11, title:"exile (feat. Bon Iver)", artist:"Taylor Swift", change:"-5"},
{rank:12, title:"Into You", artist:"Ariana Grande", change:"RE"},
{rank:13, title:"Chained To The Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"RE"},
{rank:14, title:"Legendary Lovers", artist:"Katy Perry", change:"-13"},
{rank:15, title:"Confident", artist:"Demi Lovato", change:"RE"},
{rank:16, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-6"},
{rank:17, title:"We Can't Stop", artist:"Miley Cyrus", change:"RE"},
{rank:18, title:"Side To Side (feat. Nicki Minaj)", artist:"Ariana Grande", change:"RE"},
{rank:19, title:"I Feel So Free", artist:"Madonna", change:"NEW"},
{rank:20, title:"the 1", artist:"Taylor Swift", change:"-2"},
{rank:21, title:"Low Rise Jeans", artist:"Demi Lovato", change:"RE"},
{rank:22, title:"SloMo (Eurovision's Dancebreak Edit)", artist:"Chanel", change:"NEW"},
{rank:23, title:"Legendary Lovers (Save Me)", artist:"Katy Perry & Chief Keef", change:"-21"},
{rank:24, title:"Teenage Dream", artist:"Katy Perry", change:"-19"},
{rank:25, title:"Ur So Gay", artist:"Katy Perry", change:"NEW"},],
[{rank:1, title:"Legendary Lovers", artist:"Katy Perry", change:"+13"},
{rank:2, title:"Legendary Lovers (Save Me)", artist:"Katy Perry & Chief Keef", change:"+21"},
{rank:3, title:"Cool for the Summer", artist:"Demi Lovato", change:"-2"},
{rank:4, title:"Chained To The Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"+9"},
{rank:5, title:"hate that i made you love me", artist:"Ariana Grande", change:"-3"},
{rank:6, title:"Witness", artist:"Katy Perry", change:"RE"},
{rank:7, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"RE"},
{rank:8, title:"yes, and?", artist:"Ariana Grande", change:"-3"},
{rank:9, title:"Michelle", artist:"Noam Bettan & כאן - תאגיד השידור הישראלי", change:"RE"},
{rank:10, title:"Colors", artist:"Halsey", change:"NEW"},
{rank:11, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"RE"},
{rank:12, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+4"},
{rank:13, title:"Bangaranga", artist:"DARA", change:"-9"},
{rank:14, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"RE"},
{rank:15, title:"Who's Afraid of Little Old Me?", artist:"Taylor Swift", change:"NEW"},
{rank:16, title:"bandaids", artist:"Katy Perry", change:"-13"},
{rank:17, title:"Aperture", artist:"Harry Styles", change:"RE"},
{rank:18, title:"Delicate", artist:"Taylor Swift", change:"NEW"},
{rank:19, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"RE"},
{rank:20, title:"Firework", artist:"Katy Perry", change:"-14"},
{rank:21, title:"Bon Appétit (feat. Migos)", artist:"Katy Perry", change:"RE"},
{rank:22, title:"I Kissed A Girl", artist:"Katy Perry", change:"-14"},
{rank:23, title:"Roar", artist:"Katy Perry", change:"-16"},
{rank:24, title:"Never Really Over", artist:"Katy Perry", change:"-14"},
{rank:25, title:"Confident", artist:"Demi Lovato", change:"RE"},],
[{rank:1, title:"Cool for the Summer", artist:"Demi Lovato", change:"+2"},
{rank:2, title:"Legendary Lovers", artist:"Katy Perry", change:"-1"},
{rank:3, title:"hate that i made you love me", artist:"Ariana Grande", change:"+2"},
{rank:4, title:"bandaids", artist:"Katy Perry", change:"+12"},
{rank:5, title:"Lemonade", artist:"Louis Tomlinson", change:"RE"},
{rank:6, title:"Delicate", artist:"Taylor Swift", change:"+12"},
{rank:7, title:"Ruin The Friendship", artist:"Taylor Swift", change:"RE"},
{rank:8, title:"ME! (feat. Brendon Urie of Panic! At The Disco)", artist:"Taylor Swift", change:"NEW"},
{rank:9, title:"Firework", artist:"Katy Perry", change:"+11"},
{rank:10, title:"Paper Rings", artist:"Taylor Swift", change:"NEW"},
{rank:11, title:"Stone Cold", artist:"Demi Lovato", change:"RE"},
{rank:12, title:"London Boy", artist:"Taylor Swift", change:"NEW"},
{rank:13, title:"Confident", artist:"Demi Lovato", change:"+12"},
{rank:14, title:"Bangaranga", artist:"DARA", change:"-1"},
{rank:15, title:"Roar", artist:"Katy Perry", change:"+8"},
{rank:16, title:"Never Really Over", artist:"Katy Perry", change:"+8"},
{rank:17, title:"Lover", artist:"Taylor Swift", change:"RE"},
{rank:18, title:"Hot N Cold", artist:"Katy Perry", change:"NEW"},
{rank:19, title:"hoax", artist:"Taylor Swift", change:"NEW"},
{rank:20, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"RE"},
{rank:21, title:"I Kissed A Girl", artist:"Katy Perry", change:"+1"},
{rank:22, title:"Thinking Of You", artist:"Katy Perry", change:"RE"},
{rank:23, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"-12"},
{rank:24, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"-17"},
{rank:25, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"RE"},],
[{rank:1, title:"Watch It Burn", artist:"Katy Perry", change:"NEW"},
{rank:2, title:"bandaids", artist:"Katy Perry", change:"+2"},
{rank:3, title:"Delicate", artist:"Taylor Swift", change:"+3"},
{rank:4, title:"Cool for the Summer", artist:"Demi Lovato", change:"-3"},
{rank:5, title:"Dancing on the ice", artist:"Essyla", change:"NEW"},
{rank:6, title:"Wildfire", artist:"Demi Lovato", change:"RE"},
{rank:7, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+16"},
{rank:8, title:"Stone Cold", artist:"Demi Lovato", change:"+3"},
{rank:9, title:"Look What You Made Me Do", artist:"Taylor Swift", change:"RE"},
{rank:10, title:"Confident", artist:"Demi Lovato", change:"+3"},
{rank:11, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"+13"},
{rank:12, title:"I'M HIS, HE'S MINE (feat. Doechii)", artist:"Katy Perry", change:"+13"},
{rank:13, title:"Ruin The Friendship", artist:"Taylor Swift", change:"-6"},
{rank:14, title:"Bangaranga", artist:"DARA", change:"="},
{rank:15, title:"LIFETIMES", artist:"Katy Perry", change:"RE"},
{rank:16, title:"Skyfall", artist:"Adele", change:"NEW"},
{rank:17, title:"Firework", artist:"Katy Perry", change:"-8"},
{rank:18, title:"Teenage Dream", artist:"Katy Perry", change:"RE"},
{rank:19, title:"Into Me You See", artist:"Katy Perry", change:"NEW"},
{rank:20, title:"hate that i made you love me", artist:"Ariana Grande", change:"-17"},
{rank:21, title:"ALL THE LOVE", artist:"Katy Perry", change:"RE"},
{rank:22, title:"WOMAN'S WORLD", artist:"Katy Perry", change:"RE"},
{rank:23, title:"Not Like The Movies", artist:"Katy Perry", change:"RE"},
{rank:24, title:"Chained To The Rhythm (feat. Skip Marley)", artist:"Katy Perry", change:"RE"},
{rank:25, title:"Father", artist:"Demi Lovato", change:"NEW"},],
];

LC.MO_KEYS = ["Jan 2026","Feb 2026","Mar 2026","Apr 2026","May 2026"];

LC.MO_SONGS = {
  "Jan 2026":[
    {rank:1, title:"bandaids", artist:"Katy Perry", change:"+1"},
{rank:2, title:"Hello", artist:"Adele", change:"NEW"},
{rank:3, title:"Cool for the Summer", artist:"Demi Lovato", change:"+1"},
{rank:4, title:"Confident", artist:"Demi Lovato", change:"+10"},
{rank:5, title:"Stone Cold", artist:"Demi Lovato", change:"NEW"},
{rank:6, title:"Story of My Life", artist:"One Direction", change:"NEW"},
{rank:7, title:"Tell Me You Love Me", artist:"Demi Lovato", change:"NEW"},
{rank:8, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"-2"},
{rank:9, title:"Wonder", artist:"Shawn Mendes", change:"+13"},
{rank:10, title:"Legendary Lovers", artist:"Katy Perry", change:"+15"},
  ],
  "Feb 2026":[
    {rank:1, title:"Cool for the Summer", artist:"Demi Lovato", change:"+2"},
{rank:2, title:"Teenage Dream", artist:"Katy Perry", change:"NEW"},
{rank:3, title:"Confident", artist:"Demi Lovato", change:"+1"},
{rank:4, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"NEW"},
{rank:5, title:"Hello", artist:"Adele", change:"-3"},
{rank:6, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+9"},
{rank:7, title:"Dark Horse (feat. Juicy J)", artist:"Katy Perry", change:"+1"},
{rank:8, title:"Stone Cold", artist:"Demi Lovato", change:"-3"},
{rank:9, title:"bandaids", artist:"Katy Perry", change:"-8"},
{rank:10, title:"Easy On Me", artist:"Adele", change:"NEW"},
  ],
  "Mar 2026":[
    {rank:1, title:"Birthday", artist:"Katy Perry", change:"NEW"},
{rank:2, title:"ALL THE LOVE", artist:"Katy Perry", change:"NEW"},
{rank:3, title:"LIFETIMES", artist:"Katy Perry", change:"NEW"},
{rank:4, title:"Aperture", artist:"Harry Styles", change:"+19"},
{rank:5, title:"Hello", artist:"Adele", change:"="},
{rank:6, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"+9"},
{rank:7, title:"Cool for the Summer", artist:"Demi Lovato", change:"-6"},
{rank:8, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"-2"},
{rank:9, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"+4"},
{rank:10, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"-6"},
  ],
  "Apr 2026":[
    {rank:1, title:"bandaids", artist:"Katy Perry", change:"+15"},
{rank:2, title:"Style (Taylor's Version)", artist:"Taylor Swift", change:"+8"},
{rank:3, title:"Cool for the Summer", artist:"Demi Lovato", change:"+4"},
{rank:4, title:"Sunflowers", artist:"Louis Tomlinson", change:"+10"},
{rank:5, title:"Shake It Off (Taylor's Version)", artist:"Taylor Swift", change:"+15"},
{rank:6, title:"Confident", artist:"Demi Lovato", change:"+5"},
{rank:7, title:"Wildest Dreams (Taylor's Version)", artist:"Taylor Swift", change:"-1"},
{rank:8, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"="},
{rank:9, title:"Swish Swish (feat. Nicki Minaj)", artist:"Katy Perry", change:"+3"},
{rank:10, title:"Welcome To New York (Taylor's Version)", artist:"Taylor Swift", change:"-1"},
  ],
  "May 2026":[
    {rank:1, title:"Legendary Lovers", artist:"Katy Perry", change:"+13"},
{rank:2, title:"The One That Got Away", artist:"Katy Perry", change:"NEW"},
{rank:3, title:"Thinking Of You", artist:"Katy Perry", change:"+14"},
{rank:4, title:"Bad Blood (Taylor's Version) [feat. Kendrick Lamar]", artist:"Taylor Swift", change:"+11"},
{rank:5, title:"Blank Space (Taylor's Version)", artist:"Taylor Swift", change:"+3"},
{rank:6, title:"bandaids", artist:"Katy Perry", change:"-5"},
{rank:7, title:"Bangaranga", artist:"DARA", change:"NEW"},
{rank:8, title:"Legendary Lovers (Save Me)", artist:"Katy Perry & Chief Keef", change:"NEW"},
{rank:9, title:"CANCELLED!", artist:"Taylor Swift", change:"NEW"},
{rank:10, title:"I Did Something Bad", artist:"Taylor Swift", change:"NEW"},
  ]
};

LC.MO_ARTISTS = {
  "Jan 2026":[
    {rank:1, name:"Katy Perry", genre:"Pop", change:"="},
{rank:2, name:"Adele", genre:"Soft pop", change:"NEW"},
{rank:3, name:"Demi Lovato", genre:"Pop", change:"-1"},
{rank:4, name:"Ellie Goulding", genre:"Pop", change:"-1"},
{rank:5, name:"Maroon 5", genre:"Pop", change:"NEW"},
{rank:6, name:"Shawn Mendes", genre:"Pop", change:"="},
{rank:7, name:"Miley Cyrus", genre:"Pop", change:"-3"},
{rank:8, name:"Taylor Swift", genre:"Pop", change:"-1"},
{rank:9, name:"One Direction", genre:"Pop", change:"+3"},
{rank:10, name:"Justin Bieber", genre:"Pop", change:"-5"},
  ],
  "Feb 2026":[
    {rank:1, name:"Katy Perry", genre:"Pop", change:"="},
{rank:2, name:"Adele", genre:"Soft pop", change:"="},
{rank:3, name:"Demi Lovato", genre:"Pop", change:"="},
{rank:4, name:"Taylor Swift", genre:"Pop", change:"+4"},
{rank:5, name:"Louis Tomlinson", genre:"Pop", change:"+13"},
{rank:6, name:"Ellie Goulding", genre:"Pop", change:"-2"},
{rank:7, name:"Miley Cyrus", genre:"Pop", change:"="},
{rank:8, name:"Maroon 5", genre:"Pop", change:"-3"},
{rank:9, name:"Harry Styles", genre:"Pop", change:"+7"},
{rank:10, name:"Shawn Mendes", genre:"Pop", change:"-4"},
  ],
  "Mar 2026":[
    {rank:1, name:"Katy Perry", genre:"Pop", change:"="},
{rank:2, name:"Taylor Swift", genre:"Pop", change:"+2"},
{rank:3, name:"Harry Styles", genre:"Pop", change:"+5"},
{rank:4, name:"Adele", genre:"Soft pop", change:"-2"},
{rank:5, name:"Demi Lovato", genre:"Pop", change:"-2"},
{rank:6, name:"Louis Tomlinson", genre:"Pop", change:"-1"},
{rank:7, name:"Ariana Grande", genre:"Pop", change:"+5"},
{rank:8, name:"Ellie Goulding", genre:"Pop", change:"-2"},
{rank:9, name:"Justin Bieber", genre:"Pop", change:"+5"},
{rank:10, name:"Miley Cyrus", genre:"Pop", change:"-3"},
  ],
  "Apr 2026":[
    {rank:1, name:"Taylor Swift", genre:"Pop", change:"+1"},
{rank:2, name:"Katy Perry", genre:"Pop", change:"-1"},
{rank:3, name:"Demi Lovato", genre:"Pop", change:"+2"},
{rank:4, name:"Louis Tomlinson", genre:"Pop", change:"+2"},
{rank:5, name:"Adele", genre:"Soft pop", change:"-1"},
{rank:6, name:"One Direction", genre:"Pop", change:"+8"},
{rank:7, name:"Conan Gray", genre:"Pop", change:"NEW"},
{rank:8, name:"Ariana Grande", genre:"Pop", change:"-1"},
{rank:9, name:"Ellie Goulding", genre:"Pop", change:"-1"},
{rank:10, name:"Harry Styles", genre:"Pop", change:"-7"},
  ],
  "May 2026":[{rank:1, name:"Taylor Swift", genre:"Pop", change:"="},
{rank:2, name:"Katy Perry", genre:"Pop", change:"="},
{rank:3, name:"Adele", genre:"Soft pop", change:"+2"},
{rank:4, name:"Louis Tomlinson", genre:"Pop", change:"="},
{rank:5, name:"Ariana Grande", genre:"Pop", change:"+3"},
{rank:6, name:"Lorde", genre:"Alternative", change:"NEW"},
{rank:7, name:"Conan Gray", genre:"Pop", change:"="},
{rank:8, name:"Beyoncé", genre:"Pop", change:"+4"},
{rank:9, name:"Demi Lovato", genre:"Pop", change:"-6"},
{rank:10, name:"Kyle Alessandro", genre:"Pop", change:"NEW"},
  ]
};